name: Release Workflow

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Print Release Info
      run: echo "Release triggered for version ${{ github.event.release.tag_name }}"
    - name: List Files
      run: ls -la
    - name: Print Environment Variables
      run: printenv
