name: Release Event Workflow

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Print Hello World
      run: echo "Hello, World!"
    - name: List Files
      run: ls -la
    - name: Print Environment Variables
      run: printenv
